#!/bin/bash

PROJECT=$1
DIR=$2

echo '<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">'
echo '	<modelVersion>4.0.0</modelVersion>'
echo '	<groupId>'$PROJECT'</groupId>'
echo '	<artifactId>'$PROJECT'</artifactId>'
echo '	<name>'$PROJECT'</name>'
echo '	<version>'${PROJECT:8}'-SNAPSHOT</version>'
echo 
echo '	<build>'
echo '		<plugins>'
echo '			<plugin>'
echo '				<groupId>org.apache.maven.plugins</groupId>'
echo '				<artifactId>maven-compiler-plugin</artifactId>'
echo '				<configuration>'
echo '					<source>1.5</source>'
echo '					<target>1.5</target>'
echo '				</configuration>'
echo '			</plugin>'
echo '		</plugins>'
echo '	</build>'
echo 
echo '	<dependencies>'
for JAR in `ls $DIR/*.jar`
do
	JAR_NAME=`basename $JAR .jar`
	if [ $JAR_NAME != $PROJECT ]
	 then

		echo '		<dependency>'
		echo '			<groupId>'$PROJECT'</groupId>'
		echo '			<artifactId>'$JAR_NAME'</artifactId>'
		echo '			<version>default</version>'
		echo '		</dependency>'

	else
	       echo " "

	fi

done
echo '  </dependencies>'
echo
echo '</project>'
