#!/bin/sh

#versoes="mygrid-1.1 mygrid-2.0.1 mygrid-2.1 mygrid-2.1.2 mygrid-2.1.3 mygrid-2.2 ourgrid-3.0 ourgrid-3.0.1 ourgrid-3.0.2 ourgrid-3.1 ourgrid-3.2 ourgrid-3.2.1 ourgrid-3.3 ourgrid-3.3.1 ourgrid-4.1.4 ourgrid-4.1.5"

versoes="
mygrid-2.1 \
mygrid-2.1.2 \
mygrid-2.2 \
ourgrid-3.0 \
ourgrid-3.0.1 \
ourgrid-3.0.2 \
ourgrid-3.1 \
ourgrid-3.2 \
ourgrid-3.2.1 \
ourgrid-3.3 \
ourgrid-3.3.1 \
ourgrid-4.1.4"

#versoes="mygrid-2.1.3"


DIR="/local/edigley/evolucao-ourgrid/"

for versao in $versoes
do
#	echo $versao
	artefato=`echo $versao | sed 's/\\./\\-/g'`
#	echo $artefato
	cd $versao && ../../allinone $artefato lib > $DIR""$versao".log" ; cd $DIR"/workspace" 

done


