#!/bin/bash

PROJECT=$1
DIR=$2
for JAR in `ls $DIR/*.jar`
do
	JAR_NAME=`basename $JAR .jar`
	
	if [ $JAR_NAME != $PROJECT ]

 	then
		mvn install:install-file -Dfile=$JAR -DgroupId="$PROJECT" -DartifactId=$JAR_NAME -Dversion=default -Dpackaging=jar 
	else
   		echo " "
	fi

done

